---
deployment:
  tasks:
    - export DEPLOYPATH=/home/petszania/public_html/
    - /bin/cp -R /home/petszania/repositories/petzania/* $DEPLOYPATH
    - /bin/cp /home/petszania/repositories/petzania/database.php $DEPLOYPATH/app/Config/database.php2
    - /bin/cp /home/petszania/repositories/petzania/email.php $DEPLOYPATH/app/Config/email.php2