---
deployment:
  tasks:
    - export DEPLOYPATH=/home/petszania/public_html/
    - /bin/cp -R /home/petszania/repositories/petzania/* $DEPLOYPATH
    - /bin/cp /home/petszania/repositories/database.php $DEPLOYPATH/app/Config/database.php
    - /bin/cp /home/petszania/repositories/email.php $DEPLOYPATH/app/Config/email.php